service:
  name: meetnet-proxy-api

plugins:
  - serverless-offline
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: eu-central-1
  environment:
    USERNAME: ${file(./env.${self:provider.stage}.json):username}
    PASSWORD: ${file(./env.${self:provider.stage}.json):password}

functions:
  meetnet_proxy_api:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
